# Generated by Django 4.1 on 2022-10-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('population', models.IntegerField(verbose_name='Население')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('city', models.TextField(blank=True)),
                ('phone', models.TextField(blank=True)),
                ('city_for_work', models.CharField(blank=True, max_length=200)),
                ('city_size', models.CharField(blank=True, choices=[('FIRST', 'до 50 тысяч человек'), ('SECOND', '50-150 тысяч человек'), ('THIRD', '150-300 тысяч человек'), ('FOURTH', '300-600 тысяч человек'), ('FIFTH', '600-миллион человек'), ('SIXTH', 'Свыше миллиона человек')], max_length=40)),
                ('mariage_status', models.CharField(blank=True, choices=[('FIRST', 'В браке'), ('SECOND', 'Не в браке')], max_length=40)),
                ('status', models.CharField(blank=True, choices=[('FIRST', 'Работаю'), ('SECOND', 'Не работаю сейчас'), ('THIRD', 'Веду бизнес'), ('FOURTH', 'Проблемы в бизнесе')], max_length=40)),
                ('work', models.CharField(blank=True, max_length=200)),
                ('registration', models.CharField(blank=True, choices=[('FIRST', 'Физ лицо'), ('SECOND', 'Самозанятый'), ('THIRD', 'Я ИП'), ('FOURTH', 'ООО')], max_length=40)),
                ('experience', models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=20)),
                ('sector', models.TextField(blank=True)),
                ('why', models.TextField(blank=True)),
                ('income', models.CharField(blank=True, choices=[('FIRST', 'до 30 тыс. рублей'), ('SECOND', '30-60 тыс. рублей'), ('THIRD', '60-100 тыс. рублей'), ('FOURTH', '100-150 тыс. рублей'), ('FIFTH', '150-300 тыс. рублей'), ('SIXTH', 'больше 300 тыс. рублей')], max_length=40)),
                ('satisfaction', models.CharField(blank=True, choices=[('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5'), ('SIX', '6'), ('SEVEN', '7'), ('EIGHT', '8'), ('NINE', '9'), ('TEN', '10')], max_length=20)),
                ('profit_per_month', models.CharField(blank=True, choices=[('FIRST', '50-100 тысяч в месяц'), ('SECOND', '100-200 тысяч в месяц'), ('THIRD', '200-300 тысяч в месяц'), ('FOURTH', '300-500 тысяч в месяц'), ('FIFTH', 'Более 500 тысяч в месяц')], max_length=40)),
                ('why_business1', models.TextField(blank=True)),
                ('why_business2', models.TextField(blank=True)),
                ('interest', models.TextField(blank=True)),
                ('main_or_no', models.CharField(blank=True, choices=[('Basic', 'Основной'), ('Additional', 'Дополнительный')], max_length=20)),
                ('what_need', models.TextField(blank=True)),
                ('what_sector', models.TextField(blank=True)),
                ('other_sector', models.TextField(blank=True)),
                ('when_to_begin', models.CharField(blank=True, choices=[('FIRST', 'В ближайщее время'), ('SECOND', 'В течении 2-3 недель'), ('THIRD', 'Через месяц'), ('FOURTH', 'Позже')], max_length=40)),
                ('clients', models.CharField(blank=True, choices=[('FIRST', 'Пока нет'), ('SECOND', 'Есть знакомые'), ('THIRD', 'Есть несколько клиентов'), ('FOURTH', 'Есть крупные клиенты')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('advantages', models.CharField(blank=True, max_length=200)),
                ('test_deman', models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], max_length=40)),
                ('need', models.TextField(blank=True)),
                ('when_to_gain_profit', models.CharField(blank=True, choices=[('FIRST', 'За 3 месяца'), ('SECOND', 'За 4-6 месяцев'), ('THIRD', 'За 7-12 месяцев')], max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ('created',),
            },
        ),
    ]
