# Generated by Django 4.1 on 2022-10-03 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomber', models.IntegerField(unique=True, verbose_name='Номер')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Номер слайда',
                'verbose_name_plural': 'Номера слайдов',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Название')),
                ('sub_title', models.CharField(blank=True, max_length=300, verbose_name='Дополнительное название')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('image', models.ImageField(blank=True, upload_to='pages', verbose_name='Картинка')),
                ('description', models.TextField(blank=True, verbose_name='Текст')),
                ('sub_description', models.TextField(blank=True, verbose_name='Дополнительный текст')),
                ('button_text', models.CharField(blank=True, max_length=300, verbose_name='Кнопка')),
                ('pre_button_text', models.CharField(blank=True, max_length=300, verbose_name='Дополнительная кнопка')),
                ('button_link', models.URLField(blank=True, verbose_name='Ссылка кнопки')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fild', models.CharField(blank=True, choices=[('full_name', 'full_name'), ('age', 'age'), ('email', 'email'), ('city', 'city'), ('phone', 'phone'), ('city_for_work', 'city_for_work'), ('city_size', 'city_size'), ('mariage_status', 'mariage_status'), ('status', 'status'), ('work', 'work'), ('registration', 'registration'), ('experience', 'experience'), ('sector', 'sector'), ('why', 'why'), ('income', 'income'), ('satisfaction', 'satisfaction'), ('profit_per_month', 'profit_per_month'), ('why_business1', 'why_business1'), ('why_business2', 'why_business2'), ('interest', 'interest'), ('main_or_no', 'main_or_no'), ('main_or_no', 'main_or_no'), ('what_need', 'what_need'), ('other_sector', 'other_sector'), ('when_to_begin', 'when_to_begin'), ('clients', 'clients'), ('description', 'description'), ('advantages', 'advantages'), ('test_deman', 'test_deman'), ('need', 'need'), ('when_to_gain_profit', 'when_to_gain_profit')], max_length=500, verbose_name='Поле')),
                ('fild_value', models.CharField(blank=True, max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='constructor.order', verbose_name='Номер слайда')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='TypePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип слайда',
                'verbose_name_plural': 'Типы слайдов',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='constructor.order', verbose_name='Номер слайда')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='constructor.page', verbose_name='Cлайд')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='page',
            name='type_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='constructor.typepage', verbose_name='Тип слайда'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Картинки')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='constructor.page', verbose_name='Cлайд')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ('created',),
            },
        ),
    ]
